### ISSUE TITLE
Dynamic saving of tracking results

### ISSUE THREAD

**Issue by YoussraElqattan** [0ssamaak0/DLTA-AI#31]
When a tool is left to run for a long time (tracking a 1 hour video) It crashes and gives "Killed" in the terminal. The so far tracking annotations are not saved.
![image](https://github.com/0ssamaak0/DLTA-AI/assets/96428878/3bc603bf-a2d3-43f7-8a49-b2bb753e4a01)

**Comment by Ahmed-Gazzar** [comment]
The tool now saves the tracking progress every 100 frames. So, if killed in any moment when tracking a long video, moat of the work will be saved.
