### ISSUE TITLE
Export in COCO format - error

### ISSUE THREAD

**Issue by YamenMHR** [0ssamaak0/DLTA-AI#45]
After annotating some data, I tried to export the annotation in COCO format, but I am getting the error: 
 'NoneType' object has no attribute 'filename

**Comment by 0ssamaak0** [comment]
please provide me with the following:
- what input mode did u use (Image/directory/video/video as frames)
- what model did u use for annotation

**Comment by YamenMHR** [comment]
- As input, I tried using image and directory. Both options resulted in the same error.
- I tried SAM vit_h and also creating a polygon manually.

**Comment by YamenMHR** [comment]
That is exactly what happened. Thanks for the fast response.

**Comment by kkiskkk** [comment]
May I ask where you choose to export in COCO format.
