### ISSUE TITLE
QT Error when running App

### ISSUE THREAD

**Issue by bendreality** [0ssamaak0/DLTA-AI#47]
Got this Error:

```
YOLOv8n-seg summary (fused): 195 layers, 3404320 parameters, 0 gradients, 12.6 GFLOPs
Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\DLTA-AI\DLTA_AI_app\labelme\widgets\canvas.py", line 675, in paintEvent
    p.translate(self.offsetToCenter())
  File "C:\Users\xxxx\Documents\DLTA-AI\DLTA_AI_app\labelme\widgets\canvas.py", line 822, in offsetToCenter
    return QtCore.QPoint(x, y)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
  QPoint(a0: QPoint): argument 1 has unexpected type 'float'
```

I'm getting a lot of these Qt type errors. If I fix them by converting the float to int the app works. 

I fixed the error from above for me by changing
..\DLTA-AI\DLTA_AI_app\labelme\widgets\canvas.py line 822 to

`return QtCore.QPoint(int(x), int(y))`

I'm working remote on the machine where the software is installed and using a Widescreen monitor. Maybe that's why the calculations produce floats. 

Hope it helps,
best wishes and thanks for the tool. :)

**Comment by 0ssamaak0** [comment]
Thanks a lot, we will check all of these and fix them

**Comment by 0ssamaak0** [comment]
can u provide me the following:
1- how did u install DLTA-AI, Through pip or by downloading the release
2- what python version do you have?

Thank you again

**Comment by yousefelsharkawy** [comment]
Can you please provide us with more information regarding the installation steps? Like did you manually install it or used pip install DLTA-AI, what python version are you working with and what pytorch version are you using. That would be very helpful
