### ISSUE TITLE
运行可执行文件（仅限 CPU）时候，在下载模型时发生闪退

### ISSUE THREAD

**Issue by kkiskkk** [0ssamaak0/DLTA-AI#49]
问题描述如上

**Comment by 0ssamaak0** [comment]
which version are u using?

**Comment by kkiskkk** [comment]
The version that crashed is1.0.2，But the version I installed with pip can run normally（1.1）

**Comment by 0ssamaak0** [comment]
always use lastest version to get updates and bug fixes.
