### ISSUE TITLE
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

### ISSUE THREAD

**Issue by mohamedraafat96** [0ssamaak0/DLTA-AI#52]
The app just loads the loading page before closing with this issue: 
![image](https://github.com/0ssamaak0/DLTA-AI/assets/127994871/8df02699-e43a-482f-a941-dee4d02d6f14)

**Comment by mohamedraafat96** [comment]
I solved this by upgrading NumPy to version 1.23.3
`pip install numpy --upgrade`

**Comment by 0ssamaak0** [comment]
Thank you very much, we will add it to the solutions to problems section in the user guide 😃

**Comment by 0ssamaak0** [comment]
[Done](https://0ssamaak0.github.io/DLTA-AI/installation/problems/#multiple-copies-of-the-openmp-runtime-have-been-linked-into-the-program)
