### ISSUE TITLE
How to select our own fine-tuned model in Model Explorer for labeling

### ISSUE THREAD

**Issue by Fairywyt** [0ssamaak0/DLTA-AI#54]

**Comment by 0ssamaak0** [comment]
The functionality to add any model hasn't been added yet (we are going to add it soon)

If u want to add a fine tuned model that is already in DLTA-AI (e.g., YOLOv8) you just have to add it to `DLTA-AI/DLTA_AI_app/models_menu/models_json.json` and set the path to your checkpoint, it will appear in the model explorer as a downloaded model and you can select it
