### ISSUE TITLE
QT Error when running App

### ISSUE THREAD

**Issue by zhangzscn** [0ssamaak0/DLTA-AI#56]
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/zhangzs36/anaconda3/envs/DLTA-AI/bin/platforms" ...
loaded library "/home/zhangzs36/anaconda3/envs/DLTA-AI/lib/python3.8/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
QObject::moveToThread: Current thread (0x27436a0) is not the object's thread (0x8671ba0).
Cannot move to target thread (0x27436a0)

Package             Version
------------------- --------------------
addict              2.4.0
beautifulsoup4      4.12.2
brotlipy            0.7.0
certifi             2023.5.7
cffi                1.15.1
charset-normalizer  2.0.4
click               8.1.6
colorama            0.4.6
contourpy           1.1.0
cryptography        39.0.1
cycler              0.11.0
darkdetect          0.7.1
dataclasses-json    0.5.12
DLTA-AI             1.0.2
easydict            1.10
filelock            3.12.2
filterpy            1.4.5
fonttools           4.41.0
gdown               4.7.1
idna                3.4
imageio             2.31.1
imgviz              1.7.2
importlib-metadata  6.8.0
importlib-resources 6.0.0
jeepney             0.8.0
kiwisolver          1.4.4
lap                 0.4.0
lazy_loader         0.3
loguru              0.6.0
Markdown            3.4.3
markdown-it-py      3.0.0
marshmallow         3.19.0
matplotlib          3.7.2
mdurl               0.1.2
mkl-fft             1.3.6
mkl-random          1.2.2
mkl-service         2.4.0
mmcv-full           1.7.0
mmdet               2.25.2
model-index         0.1.11
mypy-extensions     1.0.0
networkx            3.1
notify-py           0.3.42
numpy               1.24.3
onemetric           0.1.2
opencv-python       4.7.0.72
openmim             0.3.2
ordered-set         4.1.0
orjson              3.8.12
packaging           23.1
pandas              2.0.3
Pillow              9.4.0
pip                 23.1.2
platformdirs        3.9.1
psutil              5.9.4
pycocotools         2.0.6
pycparser           2.21
Pygments            2.15.1
pyOpenSSL           23.0.0
pyparsing           3.0.9
PyQt5               5.15.9
PyQt5-Qt5           5.15.2
PyQt5-sip           12.12.1
pyqtdarktheme       2.1.0
PySocks             1.7.1
python-dateutil     2.8.2
pytz                2023.3
PyWavelets          1.4.1
PyYAML              6.0.1
QtPy                2.3.1
requests            2.29.0
rich                13.4.2
scikit-image        0.20.0
scipy               1.9.1
seaborn             0.12.2
segment-anything    1.0
sentry-sdk          1.28.1
setuptools          67.8.0
six                 1.16.0
soupsieve           2.4.1
supervision         0.3.2
tabulate            0.9.0
termcolor           2.2.0
terminaltables      3.1.10
thop                0.1.1.post2209072238
tifffile            2023.7.10
tomli               2.0.1
torch               1.13.1
torchaudio          0.13.1
torchvision         0.14.1
tqdm                4.65.0
typing_extensions   4.6.3
typing-inspect      0.9.0
tzdata              2023.3
ultralytics         8.0.61
urllib3             1.26.16
wheel               0.38.4
yapf                0.40.1
zipp                3.16.2

**Comment by 0ssamaak0** [comment]
Can I know what is your machine configuration and specs?

**Comment by zhangzscn** [comment]
use the PyQt5 5.12 Solved the problem

GPU 0: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by zhangzscn** [comment]
use the pip to install
