### ISSUE TITLE
I get an error when I run it on a CPU computer.

### ISSUE THREAD

**Issue by yxl23** [0ssamaak0/DLTA-AI#57]
Is there an executable file for DLTA-AI that I can download?

**Comment by 0ssamaak0** [comment]
The Executable for lastest version 1.1 hasn't been done yet (we will make it soon).

But what type of Error you get? please provide the error message and details of your environment.

**Comment by yxl23** [comment]
Can you give me a manual about this? Yesterday's mistake may have been caused by my improper operation. Thank you

**Comment by 0ssamaak0** [comment]
About installation or use? there's acutally a [user guide](https://0ssamaak0.github.io/DLTA-AI/) (it's hasn't completed yet)

**Comment by yxl23** [comment]
Regarding the user manual, I cannot find a tutorial for object detection format. Can this tool be labeled as a box for object detection
